version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "jdxali"
#check for docker update
  - package-ecosystem: "docker"
    directory: "/Source/"
    schedule:
      interval: "daily"
    assignees:
      - "jdxali"
      - ""
    
