
name: first
on: [push]

jobs:
   job1:
      name: first job
      runs-on: ubuntu-latest
      steps: 
        - name: step one
          uses: actions/checkout@v2
        - name: step two 
          env: 
              TEST: HELLO
          run: |
               env | sort
               echo $TEST
               docker run hello-world -c "env | sort"
          
   job2:
      name: second job
      runs-on: windows-latest
      steps:
        - name: step one
          uses: actions/checkout@v2
        - name: step two
          run: "Get-ChildItem Env: | Sort-Object Name"
