
name: first
on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:    
      - main
  push:
    branches:    
      - main

jobs:
   job1:
      name: first job
      runs-on: ubuntu-latest
      steps: 
        - name: step one
          uses: actions/checkout@v2
        - name: step two 
          if: github.event_name == 'issue_comment'
          env: 
           GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
          run:  |
            gh pr comment ${{ github.event.issue.number }} --body "test comment"
               
          
   job2:
      name: second job
      runs-on: ubuntu-latest
      steps:
        - name: step one
          uses: actions/checkout@v2
        - name: step two
          run: echo "123"
